# fly.toml app configuration file generated for notes-backend-autumn-cloud-5066 on 2024-07-16T22:14:08-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notes-backend-autumn-cloud-5066'
primary_region = 'bos'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]