# fly.toml app configuration file generated for phonebook-backend-black-meadow-4882 on 2024-07-17T00:59:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-black-meadow-4882'
primary_region = 'bos'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
